# Generated by Django 4.2.14 on 2024-07-18 19:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_title_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(validators=[main.models.validate_age]),
        ),
    ]
